language: node_js
dist: xenial
sudo: false
node_js:
  - node
script: npm run build
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: bestia-game
  on:
    branch: master
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $DISCORD_WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_WEBHOOK_URL