language: node_js
node_js:
  - node
script: npm run build
deploy:
  provider: cloudfoundry
  username: YdtQsbf50R
  password:
    secure: "gBFTA4pjo7IZIJ9lbCNp8X+Gyc33rW5j81dAn1XO3XNS8iHIlUFYNWKGOA8viv5rK0eNqRX+Pi4/0VVRpH/+S6Ks5VUNZGfTnoTPkVQekeauLEOSyVty2dw1BUUisYTK3DQhuMiaceQ+n6LZEJID5IC2feVurHZMr+OQSudMT3Rhud92YhBwzvg6FDpZ2QcPdQ+AKWCiSxcUWfGKL8MtjH0RtZJT6jUrYilFit7/wD8HsCI7E3B/MHemvDrRu1v6C2fvk+f47Hu72Njw9rkpAj9O91Tk67ePGsnIc6Qgcvkf94nM5bvDEeip8BAuuA/i898dly46s+ZON95na/r0k3lyDenyT+wd5eop9odCKhl9TP43TGaBe06cMyNtP8YO+6BV1BC9y657V6x2RLqbcZjGYZD+vY3qLXi4o8Zvxwb7c0UvPnFTs7AjZo+fEhD+caZg87izqZXSX+ditNjSq8k0GhuYZXl6wP8zx1JbbA2iW4Sgg2ydqwBgkvDEMUAINuPjpQZG4yYy2nMY69AJAulbLctAiw1pfSYTzTZfJXJ0ootCOXAtLx5q2rJ5nn/BN/Wlr81OxA+Y9FLofZ5o5rv2xWjggqWpY3xGp/RRccJeqhDqxKS04/uROUgXxwapmiT3ZpI8SOB+MBSWC/TLfdMhzrWDCQbdn/wIf2Jdt4Q="
  api: https://api.cf.eu-de-darz.msh.host
  organization: meshcloudio
  space: personal-testproject