language: node_js
dist: xenial
node_js:
  - node
script: npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: bash ci/ftp_deploy.sh
  on:
    branch: master
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $DISCORD_WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_WEBHOOK_URL