
const Topics = {
  IO_SEND_MSG: 'SEND_MESSAGE',

  // I dont like this setup with the message topics. Does not feel "right"
  IO_RECV_MSG: 'RECV_MESSAGE',
  IO_RECV_ACTION: 'RECV_ACTION_MESSAGE',
  IO_RECV_COMP_MSG: 'RECV_COMP_MESSAGE',
  IO_RECV_DEL_COMP_MSG: 'RECV_DEL_COMP_MESSAGE',
  IO_RECV_ACC_INFO_MSG: 'RECV_MSG_ACCINFO',
  IO_RECV_UI_MSG: 'RECV_MSG_UI',

  CL_ACTIVE_PLAYER_CHANGED: 'CL_ACTIVE_PL_CHANGE'
};

export { Topics };
