
export const EngineEvents = {
  GAME_MOUSE_OVER: 'onMouseOver',
  GAME_MOUSE_OUT: 'onMouseOut',

  GAME_NEW_PLAYER_ENTITY: 'NEW_PLAYER_ENTITY',
  GAME_READY: 'GAME_READY',

  IO_SEND_MSG: 'SEND_MESSAGE',

  IO_RECV_MSG: 'RECV_MESSAGE',
  IO_RECV_ACTION: 'RECV_ACTION_MESSAGE',
  IO_RECV_COMP_MSG: 'RECV_COMP_MESSAGE',
  IO_RECV_DEL_COMP_MSG: 'RECV_DEL_COMP_MESSAGE',
  IO_RECV_ACC_INFO_MSG: 'RECV_MSG_ACCINFO',
  IO_RECV_UI_MSG: 'RECV_MSG_UI',
  IO_RECV_WEATHER_MSG: 'RECV_MSG_WEATHER',

  CL_ACTIVE_PLAYER_CHANGED: 'CL_ACTIVE_PL_CHANGE',
  CL_INVENTORY_CHANGED: 'CL_INVENTORY_CHANGED'
};
